### ISSUE TITLE
Did not run cleanup even task finished when i use this by aws auto-scaling

### ISSUE THREAD

**Issue by chisquare88** [OpenDroneMap/ClusterODM#77]
hello, geniuses,

did not run cleanup even task finished when I use this by AWS Auto-scaling.

when I used it last year, the instances were automatically shut down after the work was finished. I'm using it for the first time this year, and the instances aren't shutting down.

I use ClusterODM by docker-compose, and nodeodm version is "2.4.10" for compatibility  with my webodm 1.8.1.
(it looks like something problem also within webodm 1.8.1 and nodeodm 2.5.0. that is not success even all process looks like done.)

<img width="1038" alt="화면 캡처 2021-05-26 161800" src="https://user-images.githubusercontent.com/6187128/119618539-f9503d80-be3d-11eb-8b28-174940be02c6.png">
**all task was finished.**

<img width="986" alt="화면 캡처 2021-05-26 161639" src="https://user-images.githubusercontent.com/6187128/119618387-cb6af900-be3d-11eb-8952-485a143e7acc.png">
**still online even spend many times...**

``` yml
version: '2.1'
services:
  nodeodm-1:
    image: opendronemap/nodeodm:2.4.10
    container_name: nodeodm-1
    ports:
      - "3000"
    restart: on-failure:10
    oom_score_adj: 500
    entrypoint: /usr/bin/node /var/www/index.js --max_images 1 --max_concurrency 1 --max_runtime 0 -q 0
  clusterodm:
    image: opendronemap/clusterodm
    container_name: clusterodm
    ports:
      - "80:3000"
      - "8082:8080"
      - "10000:10000"
    volumes:
      - ./docker/data:/var/www/data
      - ./config.json:/var/www/config-default.json  
      - ./asr-configuration.json:/var/www/configuration.json
    restart: on-failure:10
    depends_on:
      - nodeodm-1

```
